### ISSUE TITLE
Convert main menu to a "menu" menu

### ISSUE THREAD

**Issue by hcpss-banderson** [HCPSS/hcpss_schoolsite_theme#12]
The main menu is hard coded in page.tpl.php so it has to be customized for every school. There are placeholders for stuff like "Scholarships" and "Graduation Requirements" which are not applicable to ES/MS schools.

I think what we should do is use the Main Menu and replace the menu rendered in page.tpl.php with a custom rendered version of the Main Menu.

When deploying the new theme, we just need to make sure the Main Menu is populated (manually or automatically) before hand.

**Comment by hcpss-mbarger** [comment]
@hcpss-vincevince1006 is going in now and converting the following HS main menus into Structure > Menus.  He's using the "Main menu" menu which matches the ES/MS menu usage.
- [x] ARL
- [x] Atholton HS
- [x] Centennial HS
- [x] Glenelg HS
- [x] Hammond HS
- [x] Homewood
- [x] Howard HS
- [x] Long Reach HS
- [x] Marriotts Ridge HS
- [x] Mt. Hebron HS
- [x] Oakland Mills HS
- [x] Reservoir HS
- [x] River Hill HS
- [x] Wilde Lake HS

**Comment by hcpss-vincevince1006** [comment]
Those are now converted!

**Comment by hcpss-mbarger** [comment]
Thanks!
