### ISSUE TITLE
Add an optional blog link in the school site header

### ISSUE THREAD

**Issue by hcpss-mbarger** [HCPSS/hcpss_schoolsite_theme#19]
If the school has an off-site blog, add an optional link in the header.

**Comment by hcpss-mbarger** [comment]
Addressed at the theme level in #20 & at the setting level in [HCPSS/hcpss_schoolsite_config/ Pull 1](https://github.com/HCPSS/hcpss_schoolsite_config/pull/1).

**Comment by hcpss-mbarger** [comment]
They are simple changes but @hcpss-banderson can you give them a quick review to make sure I haven't missed anything.  Thx.

**Comment by hcpss-banderson** [comment]
Perfect. I applied it as a patch and confirmed it's working.

**Comment by hcpss-mbarger** [comment]
Awesome.  Thanks.
